// mutation types
export default {
    INITIAL_GOODS_COUNT: 'INITIAL_GOODS_COUNT',

    INCREASE_GOODS_COUNT: 'INCREASE_GOODS_COUNT',

    DECREASE_GOODS_COUNT: 'DECREASE_GOODS_COUNT',

    UPDATE_GOODS_COUNT_ENTERED: 'UPDATE_GOODS_COUNT_ENTERED',

    CLEAR_CART: 'CLEAR_CART'
};
