// mutation types
export default {
    INITIAL_GOODS_COUNT: 'INITIAL_GOODS_COUNT',
    INCREASE_GOODS_COUNT: 'INCREASE_GOODS_COUNT',
    DECREASE_GOODS_COUNT: 'DECREASE_GOODS_COUNT',
    ENTER_GOODS_COUNT: 'ENTER_GOODS_COUNT',
    CLEAR_CART: 'CLEAR_CART'
};
