// mutation types
export default {
    ADD_GOODS_TO_CART: 'ADD_GOODS_TO_CART',
    INITIAL_GOODS_COUNT: 'INITIAL_GOODS_COUNT',
    INCREASE_GOODS_COUNT: 'INCREASE_GOODS_COUNT',
    DECREASE_GOODS_COUNT: 'DECREASE_GOODS_COUNT',
    ENTER_GOODS_COUNT: 'ENTER_GOODS_COUNT'
};
